name: flutter_application_scavenge
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/PFT.jpg
    - assets/images/floor_1_pft.jpg
    - assets/images/floor_2_pft.jpg
    - assets/images/floor_3_pft.jpg
    